targets:
  $default:
    builders:
      json_serializable:json_serializable:
        generate_for:
          - lib/model/**
          - lib/network/**
      copy_with_extension_gen:copy_with_extension_gen:
        generate_for:
          - lib/bloc/**
          - lib/model/**
      fast_i18n:
        options:
          input_directory: lib/i18n
          output_directory: lib/common
          output_file_name: translations.g.dart
          translate_var: S
      freezed:
        options:
