name: cloud_music
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

parameters:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  copy_with_extension: ^4.0.0
  equatable: ^2.0.3
  ffi: ^1.1.2
  fast_i18n: ^5.9.0
  flutter_bloc: ^8.0.1
  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0
  dio: ^4.0.4
  #  permission_handler: ^8.3.0

  media:
    path: media

  flutter_screenutil: 5.0.3

  logger: ^1.1.0
  retrofit: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  copy_with_extension_gen: ^4.0.0
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.5
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.1


flutter:
  assets:
    - assets/


  uses-material-design: true

